server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?userSSL=false&serverTimezone=GMT
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: localhost
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 1024
        max-wait: -1
        max-idle: 200
        min-idle: 0
    timeout: 10000

mybatis:
  type-aliases-package: com.yyx.studentad.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl